const DDGS_BASE_URL = 'http://127.0.0.1:4479';
export const MAX_POIS = 100;
export const GEMINI_QUERY_BATCH_SIZE = 60;
export const DDGS_BATCH_SIZE = 60;
export const DEFAULT_RESEARCH_SOURCE_CAP = 200;
export const MAX_RESEARCH_SOURCE_CAP = 300;
export const TARGET_SCORING_CONFIG = Object.freeze({ agendaRelevance:.30, responsibilityInvolvement:.20, policyConflict:.20, implementationRelevance:.15, documentedDisagreement:.10, evidenceAvailability:.05 });
export const queryBudget = (n) => ({ stage1: 6 * n, stage2: 8 * n, stage3: 4 * n });
export const chunk = (items, size) => Array.from({ length: Math.ceil(items.length / size) }, (_, i) => items.slice(i * size, i * size + size));
export function canonicalUrl(raw = '') { try { const url = new URL(raw); url.hash=''; ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach((k)=>url.searchParams.delete(k)); url.hostname=url.hostname.replace(/^www\./,'').toLowerCase(); url.pathname=url.pathname.replace(/\/$/,''); return url.toString(); } catch { return ''; } }
export function domainFromResult(url = '') { try { return new URL(url).hostname.replace(/^www\./,'').toLowerCase(); } catch { return ''; } }
const pause = (ms) => new Promise((r) => setTimeout(r, ms));
async function request(path, body, retries = 2) { for (let attempt=0; attempt<=retries; attempt+=1) { const controller = new AbortController(); const timer=setTimeout(()=>controller.abort(), 15000); try { const res=await fetch(`${DDGS_BASE_URL}${path}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body), signal:controller.signal }); if (!res.ok) throw new Error(`DDGS HTTP ${res.status}`); return await res.json(); } catch (error) { if (attempt===retries) throw error; await pause(300*(attempt+1)); } finally { clearTimeout(timer); } } }
export async function ddgsSearch(query, kind = 'text', maxResults = 6) { const started=performance.now?.() || Date.now(); try { const payload=await request(`/search/${kind}`, { query, region:'us-en', safesearch:'moderate', max_results:maxResults, backend:'auto' }); const results=Array.isArray(payload?.results) ? payload.results : Array.isArray(payload) ? payload : []; return { results, error:null, duration:Math.round((performance.now?.() || Date.now()) - started), backend:'auto' }; } catch (error) { return { results:[], error:String(error.message || error), duration:Math.round((performance.now?.() || Date.now()) - started), backend:'auto' }; } }
export async function extractUrl(url) { try { const payload = await request('/extract', { url, fmt:'text_plain' }, 1); return { content:String(payload?.content || '').slice(0, 5000), error:null }; } catch (error) { return { content:'', error:String(error.message || error) }; } }
export async function pooled(items, worker, limit = 6) { const output=new Array(items.length); let next=0; await Promise.all(Array.from({ length:Math.min(limit, items.length) }, async()=>{ while(next<items.length){ const i=next; next+=1; output[i]=await worker(items[i], i); } })); return output; }
export function uniqueQueries(queries = []) { const seen=new Set(); return queries.map((q)=> typeof q === 'string' ? q : q?.query).map((q)=>String(q||'').replace(/\s+/g,' ').trim()).filter((q)=>q && !seen.has(q.toLowerCase()) && seen.add(q.toLowerCase())); }
export function retrievalKind(stage, index, controversy = 0) { if (stage === 1 || stage === 2) return 'text'; return (index % 100) < Math.round((controversy <= 30 ? .25 : controversy <= 70 ? .55 : .8) * 100) ? 'news' : 'text'; }
export function normalizeResults(results, queryRecord, kind, meta = {}) { const query = typeof queryRecord === 'string' ? queryRecord : queryRecord.query; return results.map((r, index)=>{ const url=canonicalUrl(r.href || r.url || r.link); return url ? { id:`${meta.stage || 'stage'}_source_${String((meta.offset || 0)+index+1).padStart(3,'0')}`, queryId:queryRecord.id, query, stage:meta.stage, batchId:meta.batchId, searchType:kind, backend:'auto', url, canonicalUrl:url, title:String(r.title || 'Untitled source'), snippet:String(r.body || r.snippet || ''), publicationDate:r.date || r.published || '', eventDate:'', informationAvailabilityDate:'', retrievalStatus:'success', error:'', domain:domainFromResult(url), extractedText:'' } : null; }).filter(Boolean); }
export function deduplicateSources(sources) { return [...new Map(sources.map((s)=>[s.canonicalUrl, s])).values()].map((s,i)=>({ ...s, id:s.id || `source_${String(i+1).padStart(3,'0')}` })); }
export function freezeValidation({ publicationDate, eventDate, informationAvailabilityDate, freezeDate }) { const parse=(v)=>v && Number.isFinite(Date.parse(v)) ? Date.parse(v) : null; const freeze=parse(freezeDate); const pub=parse(publicationDate); const event=parse(eventDate); const avail=parse(informationAvailabilityDate); if (!freeze) return { freezeStatus:'NO_FREEZE_DATE', usable:true }; if (pub && pub <= freeze) return { freezeStatus:'PRE_FREEZE', usable:true }; if (pub && pub > freeze && event && event <= freeze && (!avail || avail <= freeze)) return { freezeStatus:'POST_FREEZE_PRE_FREEZE_EVENT', usable:true }; if ((event && event > freeze) || (avail && avail > freeze)) return { freezeStatus:'POST_FREEZE_NEW_EVENT', usable:false }; return { freezeStatus:'DATE_UNKNOWN', usable:false }; }
export function rankAndCapSources(sources, cap = DEFAULT_RESEARCH_SOURCE_CAP) { const unique=deduplicateSources(sources); const scored=unique.map((s)=>({ ...s, sourceRank: (/\.gov|\.int|un\.org|icc-cpi|icj-cij|ohchr|worldbank|imf/i.test(s.domain) ? 40 : 0) + (s.usable ? 20 : 0) + Math.min(40, String(s.snippet+s.title).length/12) })); return scored.sort((a,b)=>b.sourceRank-a.sourceRank).slice(0, Math.min(MAX_RESEARCH_SOURCE_CAP, cap)); }
export function incidentKey(e) { return `${e.target || e.country || ''}|${String(e.claim || '').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter((w)=>w.length>4).slice(0,12).sort().join(' ')}`; }
export function clusterIncidents(evidence) { const clusters=new Map(); evidence.forEach((item)=>{ const key=incidentKey(item); const current=clusters.get(key) || { id:`stage3_incident_${String(clusters.size+1).padStart(3,'0')}`, target:item.target || item.country, evidenceIds:[], claims:[], evidence:[], corroboratingSources:[] }; current.evidenceIds.push(...(item.sourceIds || [])); current.claims.push(item.claim); current.evidence.push(item); current.corroboratingSources=[...new Set([...current.corroboratingSources, ...(item.sourceIds || [])])]; clusters.set(key,current); }); return [...clusters.values()]; }
export function scoreTarget(t) { return Object.entries(TARGET_SCORING_CONFIG).reduce((sum,[k,w])=>sum + (Math.max(0, Math.min(1, Number(t[k]) || 0)) * w), 0); }
export async function retrieveQueries(queries, { controversy=0, stage, onProgress, freezeDate='', search=ddgsSearch, extract=extractUrl, store, jobId, batchPrefix=`stage${stage}` } = {}) {
  const batches=chunk(queries, DDGS_BATCH_SIZE); const allSources=[]; const logs=[]; const diagnostics={ attempted:queries.length, successful:0, failed:0, empty:0, extracted:0, usableAfterFreeze:0 };
  let completed=0;
  for (let b=0; b<batches.length; b+=1) {
    const batch=batches[b];
    console.info(`[Stage ${stage}][DDGS] batch ${b+1}/${batches.length || 1} START queries ${completed + 1}-${completed + batch.length}`);
    await store?.put('diagnostics', { id:`${jobId}_stage_${stage}_ddgs_batch_${b+1}_start`, jobId, stage:`stage_${stage}`, message:`[STAGE ${stage} DDGS BATCH ${b+1}/${batches.length || 1}]`, batch:b+1, batchTotal:batches.length || 1 });
    const rows=await pooled(batch, async(queryRecord, index)=>{ const kind=retrievalKind(stage, completed + index, controversy); const response=await search(typeof queryRecord==='string' ? queryRecord : queryRecord.query, kind); const log={ id:`${batchPrefix}_search_${String(completed+index+1).padStart(3,'0')}`, queryId:queryRecord.id, query:typeof queryRecord==='string'?queryRecord:queryRecord.query, stage:`stage_${stage}`, batchId:`${batchPrefix}_ddgs_batch_${b+1}`, searchType:kind, backend:'auto', resultCount:response.results.length, duration:response.duration, success:!response.error, error:response.error || '' }; if (response.error) diagnostics.failed+=1; else if (!response.results.length) diagnostics.empty+=1; else diagnostics.successful+=1; logs.push(log); return normalizeResults(response.results, queryRecord, kind, { stage:`stage_${stage}`, batchId:log.batchId, offset:allSources.length + index*10 }); }, 6);
    completed += batch.length;
    const flat=rows.flat(); allSources.push(...flat);
    await store?.putBatch('ddgsBatches', jobId, `stage_${stage}`, `${batchPrefix}_ddgs_batch_${b+1}`, flat, { logs:logs.slice(), completed, total:queries.length });
    const event={ stage:`stage_${stage}`, phase:'ddgs_retrieval', completed, done:completed, total:queries.length || 1, batch:b+1, batchTotal:batches.length || 1, detail:`[Stage ${stage}][DDGS] batch ${b+1}/${batches.length || 1} COMPLETE: completed=${completed} successful=${diagnostics.successful} empty=${diagnostics.empty} failed=${diagnostics.failed}` };
    await store?.putProgress(jobId, event); onProgress?.(event);
    console.info(event.detail);
  }
  const unique=rankAndCapSources(allSources.map((s)=>({ ...s, freezeDate, ...freezeValidation({ ...s, freezeDate }) })));
  const limit=Math.min(unique.length, Math.max(25, Math.min(unique.length, queries.length * 2)));
  const extracted=await pooled(unique.slice(0, limit), async(source)=>{ const page=await extract(source.url); if (page.content) diagnostics.extracted+=1; return { ...source, extractedText:page.content, extractionError:page.error }; }, 5);
  const retained=rankAndCapSources([...extracted, ...unique.slice(limit)]); diagnostics.usableAfterFreeze=retained.filter((s)=>s.usable).length;
  await store?.putBatch('sources', jobId, `stage_${stage}`, `${batchPrefix}_sources`, retained, { diagnostics });
  console.info(`[Stage ${stage}][DDGS] COMPLETE usableSources=${diagnostics.usableAfterFreeze} extracted=${diagnostics.extracted}`);
  return { sources:retained, diagnostics, logs };
}
export function newsShare(controversy) { if (controversy <= 30) return .2; if (controversy <= 60) return .5; if (controversy <= 80) return .7; return .85; }
export function allocateActorQueries(actors, budget) { if (!actors.length || budget <= 0) return actors.map((actor) => ({ ...actor, queryAllocation:0 })); const weighted=actors.map((actor)=>Math.max(1, Number(actor.relevance ?? actor.agendaRelevance) || 1)); const total=weighted.reduce((s,v)=>s+v,0); const allocation=weighted.map((v)=>Math.floor(v/total*budget)); let remaining=budget-allocation.reduce((s,v)=>s+v,0); [...weighted.keys()].sort((a,b)=>weighted[b]-weighted[a]).forEach((i)=>{ if(remaining>0){ allocation[i]+=1; remaining-=1; } }); return actors.map((actor,i)=>({ ...actor, queryAllocation:allocation[i] })); }
export function targetValue(c) { return (c.agendaRelevance || 0)*.30 + (c.evidenceStrength || 0)*.20 + (c.legalAccountability || 0)*.15 + (c.controversyFit || 0)*.15 + (c.recency || 0)*.10 + (c.sourceQuality || 0)*.07 + (c.corroboration || 0)*.03; }
