// Browser client for the official DDGS API service (`ddgs api --host 127.0.0.1 --port 4479`).
const DDGS_BASE_URL = 'http://127.0.0.1:4479';
export const MAX_POIS = 100;
export const queryBudget = (requestedPOIs) => ({ stage1: Math.round(requestedPOIs * 7.5), stage2: requestedPOIs * 10 });
export function canonicalUrl(raw = '') { try { const url = new URL(raw); url.hash = ''; ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach((key) => url.searchParams.delete(key)); url.hostname = url.hostname.replace(/^www\./, '').toLowerCase(); url.pathname = url.pathname.replace(/\/$/, ''); return url.toString(); } catch { return ''; } }
export function domainFromResult(url = '') { try { return new URL(url).hostname.replace(/^www\./, '').toLowerCase(); } catch { return ''; } }
const pause = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function request(path, body, retries = 2) { for (let attempt = 0; attempt <= retries; attempt += 1) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 15000); try { const response = await fetch(`${DDGS_BASE_URL}${path}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body), signal:controller.signal }); if (!response.ok) throw new Error(`DDGS HTTP ${response.status}`); return await response.json(); } catch (error) { if (attempt === retries) throw error; await pause(300 * (attempt + 1)); } finally { clearTimeout(timer); } } }
export async function ddgsSearch(query, kind = 'text', maxResults = 6) { try { const payload = await request(`/search/${kind}`, { query, region:'us-en', safesearch:'moderate', max_results:maxResults, backend:'auto' }); return { results:Array.isArray(payload?.results) ? payload.results : Array.isArray(payload) ? payload : [], error:null }; } catch (error) { return { results:[], error:String(error.message || error) }; } }
export async function extractUrl(url) { try { const payload = await request('/extract', { url, fmt:'text_plain' }, 1); return { content:String(payload?.content || '').slice(0, 5000), error:null }; } catch (error) { return { content:'', error:String(error.message || error) }; } }

// Every worker gets its stable input index. Results retain input order even when requests finish out of order.
export async function pooled(items, worker, limit = 6) { const output = new Array(items.length); let next = 0; await Promise.all(Array.from({ length:Math.min(limit, items.length) }, async () => { while (next < items.length) { const index = next; next += 1; output[index] = await worker(items[index], index); } })); return output; }
export function newsShare(controversy) { if (controversy <= 30) return .2; if (controversy <= 60) return .5; if (controversy <= 80) return .7; return .85; }
export function retrievalKind(stage, index, controversy = 0) { return stage === 1 ? 'text' : (index % 100) < Math.round(newsShare(controversy) * 100) ? 'news' : 'text'; }
export function uniqueQueries(queries = []) { const seen = new Set(); return queries.map((query) => String(query || '').replace(/\s+/g, ' ').trim()).filter((query) => query && !seen.has(query.toLowerCase()) && seen.add(query.toLowerCase())); }
export function allocateActorQueries(actors, budget) { if (!actors.length || budget <= 0) return actors.map((actor) => ({ ...actor, queryAllocation:0 })); const weighted = actors.map((actor) => Math.max(1, Number(actor.relevance) || 1)); const total = weighted.reduce((sum, value) => sum + value, 0); const allocation = weighted.map((value) => Math.floor(value / total * budget)); let remaining = budget - allocation.reduce((sum, value) => sum + value, 0); [...weighted.keys()].sort((a,b) => weighted[b] - weighted[a]).forEach((index) => { if (remaining > 0) { allocation[index] += 1; remaining -= 1; } }); return actors.map((actor, index) => ({ ...actor, queryAllocation:allocation[index] })); }
export function normalizeResults(results, query, kind) { return results.map((result) => { const url = canonicalUrl(result.href || result.url || result.link); return url ? { url, canonicalUrl:url, title:String(result.title || 'Untitled source'), snippet:String(result.body || result.snippet || ''), publicationDate:result.date || result.published || '', eventDate:'', informationAvailabilityDate:'', query, retrievalKind:kind, domain:domainFromResult(url), extractedText:'' } : null; }).filter(Boolean); }
export function deduplicateSources(sources) { return [...new Map(sources.map((source) => [source.canonicalUrl, source])).values()]; }
export function freezeValidation({ publicationDate, eventDate, informationAvailabilityDate, freezeDate }) { const parse = (value) => value && Number.isFinite(Date.parse(value)) ? Date.parse(value) : null; const freeze = parse(freezeDate); const publication = parse(publicationDate); const event = parse(eventDate); const available = parse(informationAvailabilityDate); if (!freeze || (!publication && !event && !available)) return { freezeStatus:'DATE_UNKNOWN', usable:false }; if (publication && publication <= freeze) return { freezeStatus:'PRE_FREEZE', usable:true }; if (publication && publication > freeze && event && event <= freeze && available && available <= freeze) return { freezeStatus:'POST_FREEZE_PRE_FREEZE_EVENT', usable:true }; if ((event && event > freeze) || (available && available > freeze)) return { freezeStatus:'POST_FREEZE_NEW_EVENT', usable:false }; return { freezeStatus:'DATE_UNKNOWN', usable:false }; }
export function incidentKey(evidence) { return `${evidence.country || ''}|${String(evidence.claim || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').split(' ').filter((word) => word.length > 4).slice(0, 12).sort().join(' ')}`; }
export function clusterIncidents(evidence) { const clusters = new Map(); evidence.forEach((item) => { const key = incidentKey(item); const incident = clusters.get(key) || { id:`incident_${clusters.size + 1}`, country:item.country, evidenceIds:[], claims:[], evidence:[], corroboratingOutlets:[] }; incident.evidenceIds.push(...item.sourceIds); incident.claims.push(item.claim); incident.evidence.push(item); clusters.set(key, incident); }); return [...clusters.values()]; }
export function targetValue(c) { return (c.agendaRelevance || 0)*.30 + (c.evidenceStrength || 0)*.20 + (c.legalAccountability || 0)*.15 + (c.controversyFit || 0)*.15 + (c.recency || 0)*.10 + (c.sourceQuality || 0)*.07 + (c.corroboration || 0)*.03; }

export async function retrieveQueries(queries, { controversy = 0, onProgress, stage, freezeDate = '', search = ddgsSearch, extract = extractUrl, extractionBudget } = {}) {
  const diagnostics = { attempted:queries.length, successful:0, failed:0, empty:0, extracted:0, usableAfterFreeze:0 }; let completed = 0;
  const results = await pooled(queries, async (query, index) => { const kind = retrievalKind(stage, index, controversy); const response = await search(query, kind); completed += 1; if (response.error) diagnostics.failed += 1; else if (!response.results.length) diagnostics.empty += 1; else diagnostics.successful += 1; onProgress?.({ stage:`STAGE ${stage} DDGS`, detail:`Stage ${stage} DDGS ${completed}/${queries.length} (${kind}, backend auto).`, done:completed, total:queries.length }); return normalizeResults(response.results, query, kind); });
  const sources = deduplicateSources(results.flat()); const limit = Math.min(sources.length, extractionBudget ?? Math.max(25, Math.min(sources.length, queries.length * 2)));
  const extracted = await pooled(sources.slice(0, limit), async (source) => { const page = await extract(source.url); if (page.content) diagnostics.extracted += 1; return { ...source, extractedText:page.content, extractionError:page.error }; }, 5);
  const dated = extracted.map((source) => ({ ...source, freezeDate:freezeDate || null, ...freezeValidation({ ...source, freezeDate }) })); diagnostics.usableAfterFreeze = dated.filter((source) => source.usable).length; return { sources:dated, diagnostics };
}
