import { callGemini, GeminiError, FOLLOW_UP_RESPONSE_SCHEMA } from './gemini.js';
import { extractJson } from './responseParser.js';
import { normalizeChit, validateMissionResponse } from './validation.js';
import { ResearchJobStore } from './researchJobStore.js';
import { queryBudget, retrieveQueries, uniqueQueries, freezeValidation, clusterIncidents, scoreTarget, GEMINI_QUERY_BATCH_SIZE, MAX_POIS, TARGET_SCORING_CONFIG } from './ddgsResearch.js';

const JSON_SCHEMA = { type:'object', properties:{ queries:{ type:'array', items:{ type:'object', properties:{ query:{ type:'string' }, searchType:{ type:'string' }, target:{ type:'string' } } } }, intelligence:{ type:'object' }, targets:{ type:'array', items:{ type:'object' } }, evidence:{ type:'array', items:{ type:'object' } }, pois:{ type:'array', items:{ type:'object' } } } };
const compact=(value,length=36000)=>JSON.stringify(value).slice(0,length);
const same=(a,b)=>String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase();
const qid=(stage,n)=>`stage${stage}_query_${String(n).padStart(3,'0')}`;
export function lengthInfo(length) { const [, min, max, lines] = [[10,8,15,'≈ 1 line'],[25,15,25,'≈ 1–2 lines'],[40,20,35,'≈ 2 lines'],[55,30,45,'≈ 2–3 lines'],[70,40,55,'≈ 3 lines'],[85,50,70,'≈ 3–4 lines'],[100,65,90,'≈ 4–5 lines']].find(([limit]) => length <= limit); return { min, max, lines, words:`approximately ${min}–${max} words` }; }
function validArtifact(name, artifact, fields) { const missing=fields.filter((f)=>artifact[f] === undefined || artifact[f] === null || (typeof artifact[f] === 'string' && !artifact[f].trim()) || (Array.isArray(artifact[f]) && !artifact[f].length)); if (missing.length) throw new GeminiError(`${name} failed validation: missing ${missing.join(', ')}. Downstream stages blocked.`, { category:'schema-failed', validationErrors:missing }); return artifact; }
async function emit(onProgress, p, store, jobId) { const total=Math.max(1, Math.trunc(Number.isFinite(p.total) ? p.total : 1)); const completed=Math.min(total, Math.max(0, Math.trunc(Number.isFinite(p.completed ?? p.done) ? (p.completed ?? p.done) : 0))); const event={ ...p, completed, done:completed, total, detail:p.detail || p.log || '' }; await store?.putProgress?.(jobId, event); onProgress?.(event); }
async function runtimeLog({ store, jobId, onProgress, stage, message, extra = {} }) { await store?.put('diagnostics', { id:`${jobId}_${stage}_log_${Date.now()}_${Math.random().toString(16).slice(2)}`, jobId, stage, message, ...extra }); await emit(onProgress, { stage, phase:'runtime_log', completed:extra.completed ?? 0, total:extra.total ?? 1, detail:message }, store, jobId); }
async function setStageStatus(store, jobId, stage, status, extra = {}) { await store.putStageMetadata(jobId, stage, status, extra); }
async function requireCheckpoint(store, jobId, stage) { const checkpoint=await store.getArtifact(jobId, stage); const metadata=await store.getStageMetadata(jobId, stage); if (!checkpoint || metadata?.status !== 'COMPLETE') throw new GeminiError(`${stage} checkpoint is not complete and persisted. Downstream stage blocked.`, { category:'stage-gate-failed' }); return checkpoint.artifact; }

/** The single authoritative Gemini response lifecycle for every research artifact. */
async function requestStageJson({ stage, apiKey, prompt, modelSelection, store, jobId, onProgress, validate, schemaDescription, attachments=[] }) {
  const gemini=modelSelection?.callGeminiImpl || callGemini;
  let rawText=''; let failure=null;
  for (let attempt=0; attempt<3; attempt+=1) {
    try {
      await runtimeLog({ store, jobId, onProgress, stage, message:`[${stage.replace('_',' ').toUpperCase()}] Gemini request started${attempt ? ` (repair ${attempt}/2)` : ''}` });
      const requestPrompt=attempt ? `${prompt}\n\nSTRUCTURED REPAIR REQUEST\nStage: ${stage}\nRequired schema: ${schemaDescription}\nValidation/parse errors: ${failure?.message || 'unknown'}\nOriginal response: ${rawText}\nReturn only corrected JSON. Do not manufacture missing facts, sources, URLs, or IDs.` : prompt;
      const response=await gemini(apiKey, requestPrompt, { ...modelSelection, schema:JSON_SCHEMA, timeoutMs:70000, attachments });
      rawText=response?.text;
      if (typeof rawText !== 'string' || !rawText.trim()) throw new GeminiError('Gemini response was empty.', { category:'empty-response' });
      await runtimeLog({ store, jobId, onProgress, stage, message:`[${stage.replace('_',' ').toUpperCase()}] Gemini response received` });
      const parsed=extractJson(rawText);
      await runtimeLog({ store, jobId, onProgress, stage, message:`[${stage.replace('_',' ').toUpperCase()}] Response parsed` });
      const artifact=validate(parsed);
      await runtimeLog({ store, jobId, onProgress, stage, message:`[${stage.replace('_',' ').toUpperCase()}] Validation passed` });
      return artifact;
    } catch (error) {
      failure=error instanceof GeminiError ? error : new GeminiError(`PARSE_FAILED: ${error.message || error}`, { category:'parse-failed', cause:error });
      await store.put('errors', { id:`${jobId}_${stage}_gemini_${attempt + 1}_${Date.now()}`, jobId, stage, attempt:attempt + 1, error:failure.message, category:failure.category || 'schema-failed', rawResponse:rawText });
      if (!['parse-failed','schema-failed','empty-response'].includes(failure.category)) throw failure;
      if (attempt < 2) await runtimeLog({ store, jobId, onProgress, stage, message:`[${stage.replace('_',' ').toUpperCase()}] FAILED; Retrying with structured repair...` });
    }
  }
  throw new GeminiError(`${stage} failed after bounded parse/schema repair retries: ${failure?.message || 'unknown error'}`, { category:'stage-gate-failed', cause:failure });
}
function assertQueries(stage, queries) { if (!queries.length) throw new GeminiError(`Stage ${stage} failed: Gemini produced zero valid queries after retry. Downstream stages blocked.`, { category:'stage-gate-failed' }); }
function assertRetrieval(stage, retrieval) { if (retrieval.diagnostics.failed === retrieval.diagnostics.attempted && retrieval.diagnostics.attempted > 0) throw new GeminiError(`Stage ${stage} failed: DDGS unavailable or every query failed. Downstream stages blocked.`, { category:'ddgs-unavailable' }); if (!retrieval.sources.length) throw new GeminiError(`Stage ${stage} failed: DDGS retrieval produced zero usable sources. Downstream stages blocked.`, { category:'stage-gate-failed' }); }
async function geminiQueryBatches({ stage, apiKey, modelSelection, budget, context, store, jobId, promptBase, onProgress }) {
  let queries=[]; let batchNo=0;
  while (queries.length < budget) {
    const want=Math.min(GEMINI_QUERY_BATCH_SIZE, budget - queries.length); batchNo+=1;
    await runtimeLog({ store, jobId, onProgress, stage:`stage_${stage}`, message:`[STAGE ${stage} GEMINI BATCH ${batchNo}/${Math.ceil(budget/GEMINI_QUERY_BATCH_SIZE)}]`, extra:{ completed:queries.length, total:budget, batch:batchNo, batchTotal:Math.ceil(budget/GEMINI_QUERY_BATCH_SIZE) } });
    const response=await requestStageJson({ stage:`stage_${stage}`, apiKey, modelSelection, store, jobId, onProgress, schemaDescription:'{queries:[{query:string,searchType:string,target?:string}]} with at least one query', prompt:`${promptBase}\nReturn strict JSON {queries:[{query,searchType,target}]} with up to ${want} NEW non-duplicate queries for Stage ${stage} only. Existing queries: ${compact(queries.map((q)=>q.query),10000)}. Context: ${compact(context)}`, validate:(parsed)=>validArtifact(`Stage ${stage} query batch`, parsed, ['queries']) });
    const newQueries=uniqueQueries(response.queries || []).filter((q)=>!queries.some((x)=>same(x.query,q))).slice(0,want).map((query,i)=>({ id:qid(stage,queries.length+i+1), stage:`stage_${stage}`, batchId:`stage${stage}_query_batch_${batchNo}`, query, status:'valid' }));
    await store.putBatch('queryBatches', jobId, `stage_${stage}`, `stage${stage}_query_batch_${batchNo}`, newQueries, { requested:want, invalidCount:Math.max(0,(response.queries||[]).length-newQueries.length) });
    for (const item of newQueries) await runtimeLog({ store, jobId, onProgress, stage:`stage_${stage}`, message:`[Stage ${stage}][Query ${item.id.match(/\d+$/)?.[0] || item.id}] ${item.query}`, extra:{ completed:queries.length, total:budget, queryId:item.id, batch:batchNo, batchTotal:Math.ceil(budget/GEMINI_QUERY_BATCH_SIZE) } });
    await runtimeLog({ store, jobId, onProgress, stage:`stage_${stage}`, message:`[Stage ${stage}] Gemini query batch ${batchNo}/${Math.ceil(budget/GEMINI_QUERY_BATCH_SIZE)} COMPLETE: ${newQueries.length} queries persisted`, extra:{ completed:queries.length + newQueries.length, total:budget, batch:batchNo, batchTotal:Math.ceil(budget/GEMINI_QUERY_BATCH_SIZE) } });
    queries=[...queries,...newQueries];
    if (!newQueries.length) { await store.put('errors',{ id:`${jobId}_stage_${stage}_query_batch_${batchNo}_empty`, jobId, stage:`stage_${stage}`, batchId:`stage${stage}_query_batch_${batchNo}`, error:'Gemini returned zero valid queries for this batch.' }); if (batchNo < 3) continue; break; }
  }
  return queries;
}

export async function stage0BuildContextIntelligence({ form, sliders, poiCount, modelSelection, onProgress, store, jobId }) {
  const input={ committee:form.committee, mandate:form.mandate || form.committee, agenda:form.agenda, portfolioCountry:form.portfolio, freezeDate:form.freezeDate || null, requestedPOIs:poiCount, sliders, researchNotes:{ label:'USER_PROVIDED_CONTEXT', text:form.researchNotes || '' }, backgroundGuide:{ name:form.backgroundGuideName, text:form.backgroundGuideText || form.backgroundGuide?.text || '', attached:Boolean(form.backgroundGuide) } };
  await setStageStatus(store, jobId, 'stage_0', 'RUNNING'); await runtimeLog({ store, jobId, onProgress, stage:'stage_0', message:'[STAGE 0 START]', extra:{ completed:0, total:1 } });
  await emit(onProgress,{ stage:'stage_0', phase:'gemini_context', completed:0, total:1, detail:'Stage 0 — Gemini summarizing context and Background Guide.' }, store, jobId);
  const artifact=await requestStageJson({ stage:'stage_0', apiKey:form.apiKey, modelSelection, store, jobId, onProgress, attachments:form.backgroundGuide?.data ? [form.backgroundGuide] : [], schemaDescription:'MASTER_CONTEXT_PACKET {committee,committeeMandate,agenda,agendaInterpretation,portfolioCountry,portfolioStance,researchNotes,backgroundGuideSummary,freezeDate,freezeDateAnalysis,researchPriorities}', prompt:`Stage 0 Context Intelligence. Extract/summarize any Background Guide attachment. Label user notes exactly USER_PROVIDED_CONTEXT and do not treat them as verified evidence. Return {intelligence:{committee,agenda,agendaInterpretation,committeeMandate,backgroundGuideSummary,keyIssues,definitions,historicalContext,mechanisms,treaties,resolutions,relevantInstitutions,importantDates,ambiguities,researchPriorities,portfolioCountry,portfolioStance,freezeDate,freezeDateAnalysis,researchNotes}}. Input:${compact(input)}`, validate:(intelligence)=>validArtifact('MASTER_CONTEXT_PACKET',{ sourceType:'MASTER_CONTEXT_PACKET', ...input, ...(intelligence.intelligence || intelligence), committee:input.committee, agenda:input.agenda, portfolioCountry:input.portfolioCountry, researchNotes:input.researchNotes, freezeDate:input.freezeDate, userResearchNotes:{ label:'USER_PROVIDED_CONTEXT', text:form.researchNotes || '' } }, ['committee','committeeMandate','agenda','agendaInterpretation','portfolioCountry','portfolioStance','researchNotes','backgroundGuideSummary','freezeDateAnalysis','researchPriorities']) });
  await store.putArtifact(jobId,'stage_0',artifact); await setStageStatus(store, jobId, 'stage_0', 'COMPLETE'); await runtimeLog({ store, jobId, onProgress, stage:'stage_0', message:'[STAGE 0] IndexedDB checkpoint saved' }); await runtimeLog({ store, jobId, onProgress, stage:'stage_0', message:'[STAGE 0 COMPLETE]', extra:{ completed:1, total:1 } }); return artifact;
}

export async function stage1PortfolioAgenda({ form, masterContext, poiCount, modelSelection, onProgress, store, jobId }) {
  masterContext=await requireCheckpoint(store, jobId, 'stage_0'); await setStageStatus(store, jobId, 'stage_1', 'RUNNING'); await runtimeLog({ store, jobId, onProgress, stage:'stage_1', message:'[STAGE 1 START] Context artifact loaded', extra:{ completed:0, total:1 } });
  const budget=queryBudget(poiCount).stage1;
  const queries=await geminiQueryBatches({ stage:1, apiKey:form.apiKey, modelSelection, budget, context:masterContext, store, jobId, onProgress, promptBase:'Stage 1 Portfolio + Agenda Intelligence. Answer WHAT MATTERS, not who to attack. Do NOT search scandals/corruption/dirt/controversy. Generate portfolio stance, mandate, actors, mechanisms, treaties, voting, implementation and disagreement queries influenced by Stage 0.' });
  assertQueries(1, queries);
  const retrieval=await retrieveQueries(queries,{ stage:1, onProgress, freezeDate:form.freezeDate, store, jobId, batchPrefix:'stage1', search:form.search, extract:form.extract });
  assertRetrieval(1, retrieval);
  const artifact=await requestStageJson({ stage:'stage_1', apiKey:form.apiKey, modelSelection, store, jobId, onProgress, schemaDescription:'PORTFOLIO_AGENDA_INTELLIGENCE_PACKET with agendaAnalysis, portfolioPosition, and relevantActors', prompt:`Stage 1 synthesis. Return {intelligence:{agendaAnalysis,mandateLimitations,portfolioPosition,portfolioObjectives,relevantActors,institutions,mechanisms,policies,treaties,resolutions,disagreements,evidence,researchGaps,queriesExecuted,sourcesDiscovered}}. Do NOT call actors targets. Master:${compact(masterContext,12000)} Sources:${compact(retrieval.sources)}`, validate:(synthesis)=>validArtifact('PORTFOLIO_AGENDA_INTELLIGENCE_PACKET',{ sourceType:'PORTFOLIO_AGENDA_INTELLIGENCE_PACKET', ...(synthesis.intelligence || synthesis), queriesExecuted:queries.length, sourcesDiscovered:retrieval.sources.length, sources:retrieval.sources, diagnostics:retrieval.diagnostics, progress:{ queriesGenerated:queries.length, queriesExecuted:retrieval.diagnostics.attempted, successfulQueries:retrieval.diagnostics.successful, failedQueries:retrieval.diagnostics.failed, resultsRetrieved:retrieval.logs.reduce((sum, l)=>sum + l.resultCount, 0), uniqueSources:retrieval.sources.length, incidents:0, evidence:0, targets:0 } }, ['agendaAnalysis','portfolioPosition','relevantActors']) });
  await store.putArtifact(jobId,'stage_1',artifact); await setStageStatus(store, jobId, 'stage_1', 'COMPLETE'); await runtimeLog({ store, jobId, onProgress, stage:'stage_1', message:'[STAGE 1] IndexedDB checkpoint saved' }); await runtimeLog({ store, jobId, onProgress, stage:'stage_1', message:'[STAGE 1 COMPLETE]', extra:{ completed:1, total:1 } }); return artifact;
}

export async function stage2TargetDiscovery({ form, masterContext, portfolioAgenda, selectedTargets = [], targetingMode, poiCount, modelSelection, onProgress, store, jobId }) {
  portfolioAgenda=await requireCheckpoint(store, jobId, 'stage_1'); await setStageStatus(store, jobId, 'stage_2', 'RUNNING'); await runtimeLog({ store, jobId, onProgress, stage:'stage_2', message:'[STAGE 2 START] Stage 1 artifact loaded', extra:{ completed:0, total:1 } });
  const manual=selectedTargets.filter((t)=>!same(t.name,form.portfolio) && !same(t.iso,form.portfolio)).map((t,i)=>({ id:`stage2_target_manual_${String(i+1).padStart(3,'0')}`, country:t.name, iso:t.iso, selectionType:'USER_SELECTED_OPPOSITION', agendaRelevance:0, challengeability:0, reason:'User-selected opposition; no automatic score inflation.', evidenceIds:[] }));
  const budget=queryBudget(poiCount).stage2;
  const queries=await geminiQueryBatches({ stage:2, apiKey:form.apiKey, modelSelection, budget, context:{ masterContext, portfolioAgenda, manual, scoring:TARGET_SCORING_CONFIG }, store, jobId, onProgress, promptBase:'Stage 2 Target Discovery / Opposition Selection. Core task: determine which countries ChitForge should target with POIs. Generate only strategic challengeability/relevance queries, not dirt/scandal queries. Selection must be agenda evidence-based, not power or controversy.' });
  assertQueries(2, queries);
  const retrieval=await retrieveQueries(queries,{ stage:2, onProgress, freezeDate:form.freezeDate, store, jobId, batchPrefix:'stage2', search:form.search, extract:form.extract });
  assertRetrieval(2, retrieval);
  const response=await requestStageJson({ stage:'stage_2', apiKey:form.apiKey, modelSelection, store, jobId, onProgress, schemaDescription:'TARGET_POOL {targets:[{country, agendaRelevance, challengeability, reason}]}', prompt:`Stage 2 target scoring. Produce TARGET_POOL JSON {targets:[{country,iso,selectionType:'AUTO_DISCOVERED',agendaRelevance,challengeability,responsibilityInvolvement,policyConflict,implementationRelevance,documentedDisagreement,evidenceAvailability,reason,evidenceIds}]}. Exclude portfolio ${form.portfolio}. Do not use unrelated scandals. Scores 0-1. Manual targets pass validation separately and must not inflate AUTO score. Sources:${compact(retrieval.sources)} Context:${compact({masterContext,portfolioAgenda,manual},20000)}`, validate:(parsed)=>validArtifact('TARGET_POOL Gemini response',parsed,['targets']) });
  const auto=(response.targets || []).filter((t)=>t.country && !same(t.country,form.portfolio) && !same(t.iso,form.portfolio)).map((t,i)=>({ id:`stage2_target_${String(i+1).padStart(3,'0')}`, ...t, selectionType:'AUTO_DISCOVERED', agendaRelevance:Math.max(0,Math.min(1,Number(t.agendaRelevance)||0)), challengeability:Math.max(0,Math.min(1,Number(t.challengeability)||0)), targetScore:scoreTarget(t), evidenceIds:Array.isArray(t.evidenceIds)?t.evidenceIds:[] })).sort((a,b)=>b.targetScore-a.targetScore);
  const targets=(targetingMode === 'selected_only' ? [] : auto).concat(manual);
  const artifact=validArtifact('TARGET_POOL',{ sourceType:'TARGET_POOL', targets, autoDiscovered:auto, userSelectedOpposition:manual, scoringConfig:TARGET_SCORING_CONFIG, queriesExecuted:queries.length, sources:retrieval.sources, diagnostics:retrieval.diagnostics, progress:{ queriesGenerated:queries.length, queriesExecuted:retrieval.diagnostics.attempted, successfulQueries:retrieval.diagnostics.successful, failedQueries:retrieval.diagnostics.failed, resultsRetrieved:retrieval.logs.reduce((sum, l)=>sum + l.resultCount, 0), uniqueSources:retrieval.sources.length, incidents:0, evidence:0, targets:targets.length } }, ['targets']);
  if (!targets.length) throw new GeminiError('Stage 2 failed validation: TARGET_POOL is empty. Stage 3 blocked.', { category:'stage-gate-failed' });
  await store.putArtifact(jobId,'stage_2',artifact); await store.putBatch('targets',jobId,'stage_2','stage2_target_pool',targets); await setStageStatus(store, jobId, 'stage_2', 'COMPLETE'); await runtimeLog({ store, jobId, onProgress, stage:'stage_2', message:'[STAGE 2] IndexedDB checkpoint saved' }); await runtimeLog({ store, jobId, onProgress, stage:'stage_2', message:'[STAGE 2 COMPLETE]', extra:{ completed:1, total:1 } }); return artifact;
}

export async function stage3AccountabilityResearch({ form, sliders, poiCount, masterContext, portfolioAgenda, targetPool, modelSelection, onProgress, store, jobId }) {
  targetPool=await requireCheckpoint(store, jobId, 'stage_2'); await setStageStatus(store, jobId, 'stage_3', 'RUNNING'); await runtimeLog({ store, jobId, onProgress, stage:'stage_3', message:'[STAGE 3 START] Target pool loaded', extra:{ completed:0, total:1, inherited:['MASTER_CONTEXT_PACKET','PORTFOLIO_AGENDA_INTELLIGENCE_PACKET','TARGET_POOL'] } });
  const budget=queryBudget(poiCount).stage3;
  const queries=await geminiQueryBatches({ stage:3, apiKey:form.apiKey, modelSelection, budget, context:{ masterContext, portfolioAgenda, targetPool, sliders }, store, jobId, onProgress, promptBase:'Stage 3 Dirt / Accountability Research. Research ONLY validated Stage 2 targets. Gemini determines relevant categories: malpractice, misconduct, corruption, policy/implementation failures, treaty/legal/voting contradictions, sanctions, court rulings, official criticism. Preserve ALLEGED vs CONFIRMED.' });
  assertQueries(3, queries);
  const retrieval=await retrieveQueries(queries,{ stage:3, controversy:sliders.controversy, onProgress, freezeDate:form.freezeDate, store, jobId, batchPrefix:'stage3', search:form.search, extract:form.extract });
  assertRetrieval(3, retrieval);
  const response=await requestStageJson({ stage:'stage_3', apiKey:form.apiKey, modelSelection, store, jobId, onProgress, schemaDescription:'TARGET_INTELLIGENCE evidence array with target, claim, epistemicStatus and sourceIds', prompt:`Stage 3 evidence processing. Return {evidence:[{target,claim,category,eventDate,publicationDate,informationAvailabilityDate,epistemicStatus,agendaRelevance,evidenceStrength,sourceQuality,corroboration,primarySourceAvailable,sourceIds}]}. Use only source IDs supplied. Never fabricate URLs. Unknown-date evidence is not final. Sources:${compact(retrieval.sources)} Targets:${compact(targetPool.targets)}`, validate:(parsed)=>validArtifact('TARGET_INTELLIGENCE_PACKET Gemini response', parsed, ['evidence']) });
  const validIds=new Set(retrieval.sources.map((s)=>s.id));
  const allowedEpistemic=new Set(['ALLEGED','INVESTIGATED','REPORTED','DISPUTED','CONFIRMED','COURT_ESTABLISHED','OFFICIALLY_DOCUMENTED']);
  const evidence=(response.evidence || []).map((e,i)=>{ const sourceIds=(e.sourceIds||[]).filter((id)=>validIds.has(id)); const source=retrieval.sources.find((item)=>item.id===sourceIds[0]); return { id:`stage3_evidence_${String(i+1).padStart(3,'0')}`, ...e, sourceIds, sourceId:sourceIds[0], url:source?.url || '', title:source?.title || '', publicationDate:e.publicationDate || source?.publicationDate || '', country:e.target, freezeDate:form.freezeDate || null, ...freezeValidation({ ...e, publicationDate:e.publicationDate || source?.publicationDate, freezeDate:form.freezeDate }) }; }).filter((e)=>e.sourceIds.length && e.usable && allowedEpistemic.has(String(e.epistemicStatus || '').toUpperCase()) && targetPool.targets.some((t)=>same(t.country,e.target)));
  const incidents=clusterIncidents(evidence);
  const artifact=validArtifact('TARGET_INTELLIGENCE_PACKET',{ sourceType:'TARGET_INTELLIGENCE_PACKET', evidence, incidents, targets:targetPool.targets, sources:retrieval.sources, diagnostics:retrieval.diagnostics, queriesExecuted:queries.length, inheritedArtifacts:['MASTER_CONTEXT_PACKET','PORTFOLIO_AGENDA_INTELLIGENCE_PACKET','TARGET_POOL'], progress:{ queriesGenerated:queries.length, queriesExecuted:retrieval.diagnostics.attempted, successfulQueries:retrieval.diagnostics.successful, failedQueries:retrieval.diagnostics.failed, resultsRetrieved:retrieval.logs.reduce((sum, l)=>sum + l.resultCount, 0), uniqueSources:retrieval.sources.length, incidents:incidents.length, evidence:evidence.length, targets:targetPool.targets.length } }, ['evidence','incidents']);
  if (!evidence.length) throw new GeminiError('Stage 3 failed validation: no freeze-valid evidence claims with stored source IDs. Stage 4 blocked.', { category:'stage-gate-failed' });
  await store.putArtifact(jobId,'stage_3',artifact); await store.putBatch('evidence',jobId,'stage_3','stage3_evidence_graph',evidence); await store.putBatch('incidents',jobId,'stage_3','stage3_incidents',incidents); await setStageStatus(store, jobId, 'stage_3', 'COMPLETE'); await runtimeLog({ store, jobId, onProgress, stage:'stage_3', message:'[STAGE 3] IndexedDB checkpoint saved' }); await runtimeLog({ store, jobId, onProgress, stage:'stage_3', message:'[STAGE 3 COMPLETE]', extra:{ completed:1, total:1 } }); return artifact;
}

function evidenceFor(ids, packet) { const wanted=new Set(ids); return packet.sources.filter((s)=>wanted.has(s.id)); }
function epistemicPrefix(status) { return ({ ALLEGED:'Reports have raised allegations', INVESTIGATED:'An investigation found', REPORTED:'Reports indicate', DISPUTED:'Reports have alleged this, while the target disputes it' })[status] || ''; }
export async function stage4GeneratePOIs({ form, sliders, poiCount, masterContext, portfolioAgenda, targetPool, targetIntelligence, modelSelection, onProgress, store, jobId }) {
  targetIntelligence=await requireCheckpoint(store, jobId, 'stage_3'); await setStageStatus(store, jobId, 'stage_4', 'RUNNING'); await runtimeLog({ store, jobId, onProgress, stage:'stage_4', message:'[STAGE 4 START] Target intelligence loaded', extra:{ completed:0, total:poiCount, inherited:['MASTER_CONTEXT_PACKET','PORTFOLIO_AGENDA_INTELLIGENCE_PACKET','TARGET_POOL','TARGET_INTELLIGENCE_PACKET'] } });
  const info=lengthInfo(sliders.length); await emit(onProgress,{ stage:'stage_4', phase:'poi_generation', completed:0, total:poiCount, detail:`Stage 4 — Generating POI 0/${poiCount}.` }, store, jobId);
  const prompt=`Stage 4 Evidence-Bound POI Generation. Receives ONLY validated artifacts. Generate exactly ${poiCount} POIs when evidence permits. Output {pois:[{target,poi,evidenceIds,classification,epistemicStatus,sliderCompliance}]}. Evidence IDs only from incidents/evidence; never URLs. Backend resolves URLs. Prefer contradiction/legal/treaty/implementation/policy-vs-action/accountability traps only when supported. Do not invent impossible choices. Aggression ${sliders.aggression}=directness only; controversy ${sliders.controversy}=evidence selection only; diplomacy ${sliders.diplomacy}=cushioning; length ${info.min}-${info.max} words. sliderCompliance must echo all slider values. Prefix uncertainty (${epistemicPrefix('ALLEGED')}). Context:${compact(masterContext,8000)} Portfolio:${compact(portfolioAgenda,8000)} TargetPool:${compact(targetPool.targets,10000)} Incidents:${compact(targetIntelligence.incidents,30000)} Evidence:${compact(targetIntelligence.evidence,20000)}`;
  const generated=(await requestStageJson({ stage:'stage_4', apiKey:form.apiKey, modelSelection, store, jobId, onProgress, schemaDescription:'POI_GENERATION_PACKET {pois:[{target,poi,evidenceIds,classification,sliderCompliance}]}', prompt, validate:(parsed)=>validArtifact('POI_GENERATION_PACKET Gemini response',parsed,['pois']) })).pois; const valid=[]; const used=new Set();
  const accept=(p)=>{ const ids=p.evidenceIds || []; const evidence=evidenceFor(ids,targetIntelligence); const words=String(p.poi||'').trim().split(/\s+/).filter(Boolean).length; const slidersMatch=['aggression','controversy','diplomacy','length'].every((k)=>Number(p.sliderCompliance?.[k])===Number(sliders[k])); if (!p.poi || !targetPool.targets.some((t)=>same(t.country,p.target)) || same(p.target,form.portfolio) || !evidence.length || words<info.min || words>info.max || !slidersMatch || ids.some((id)=>/^https?:/i.test(id)) || used.has(ids.join('|'))) return false; used.add(ids.join('|')); valid.push({ ...p, evidence }); emit(onProgress,{ stage:'stage_4', phase:'poi_generation', completed:valid.length, total:poiCount, detail:`Stage 4 — Generating POI ${valid.length}/${poiCount}.` }, store, jobId); return true; };
  generated.forEach(accept);
  const artifact={ sourceType:'POI_GENERATION_PACKET', pois:valid, requested:poiCount, shortfall:Math.max(0,poiCount-valid.length), evidenceMappings:valid.map((p,i)=>({ id:`stage4_poi_${String(i+1).padStart(3,'0')}`, target:p.target, evidenceIds:p.evidenceIds })) };
  if (valid.length !== poiCount) throw new GeminiError(`Stage 4 failed validation: generated ${valid.length}/${poiCount} requested POIs.`, { category:'stage-gate-failed' }); await store.putArtifact(jobId,'stage_4',artifact); await store.putBatch('pois',jobId,'stage_4','stage4_pois',artifact.pois); await setStageStatus(store, jobId, 'stage_4', 'COMPLETE'); await runtimeLog({ store, jobId, onProgress, stage:'stage_4', message:'[STAGE 4] IndexedDB checkpoint saved' }); await runtimeLog({ store, jobId, onProgress, stage:'stage_4', message:'[STAGE 4 COMPLETE]', extra:{ completed:poiCount, total:poiCount } }); return artifact;
}

export async function generateMission(args) {
  const { form, sliders, selectedTargets, targetingMode, includeFollowUp, poiCount, onProgress, modelSelection, search, extract } = args;
  const runtimeForm = { ...form, search, extract };
  if (!Number.isInteger(poiCount) || poiCount < 1 || poiCount > MAX_POIS) throw new GeminiError('POI count must be between 1 and 100.', { category:'invalid-poi-count' });
  const store=await ResearchJobStore.create(); const job=await store.createJob({ form:{ ...runtimeForm, apiKey:'REDACTED', search:undefined, extract:undefined }, sliders, selectedTargets, targetingMode, poiCount }); const jobId=job.id;
  let activeStage='stage_0';
  try {
    const masterContext=await stage0BuildContextIntelligence({ form:runtimeForm, sliders, poiCount, modelSelection, onProgress, store, jobId });
    activeStage='stage_1'; const portfolioAgenda=await stage1PortfolioAgenda({ form:runtimeForm, masterContext, poiCount, modelSelection, onProgress, store, jobId });
    activeStage='stage_2'; const targetPool=await stage2TargetDiscovery({ form:runtimeForm, masterContext, portfolioAgenda, selectedTargets, targetingMode, poiCount, modelSelection, onProgress, store, jobId });
    activeStage='stage_3'; const targetIntelligence=await stage3AccountabilityResearch({ form:runtimeForm, sliders, poiCount, masterContext, portfolioAgenda, targetPool, modelSelection, onProgress, store, jobId });
    activeStage='stage_4'; const output=await stage4GeneratePOIs({ form:runtimeForm, sliders, poiCount, masterContext, portfolioAgenda, targetPool, targetIntelligence, modelSelection, onProgress, store, jobId });
    const chits=output.pois.map((p)=>normalizeChit({ target:p.target, poi:p.poi, evidence:p.evidence, classification:p.classification, legalTacticalTypes:[p.classification], epistemicStatus:p.epistemicStatus, sliderCompliance:p.sliderCompliance, pressurePoint:{ portfolioPosition:portfolioAgenda.portfolioPosition, targetPositionAction:p.evidence?.[0]?.snippet || '', conflict:p.evidence?.[0]?.title || '', agendaRelevance:'Validated Stage 3 evidence' }, tacticalImpact:'Evidence-backed agenda pressure point.' }, { form:runtimeForm, sliders, includeFollowUp }));
    const researchPacket={ jobId, masterContext, portfolioAgenda, targetPool, targetIntelligence, poiPacket:output, stats:{ stage1Queries:portfolioAgenda.queriesExecuted, stage2Queries:targetPool.queriesExecuted, stage3Queries:targetIntelligence.queriesExecuted, retainedUrls:targetIntelligence.sources.length, incidents:targetIntelligence.incidents.length }, sources:targetIntelligence.sources };
    const mission={ chits, targets:targetPool.targets.map((t)=>({ country:t.country, pois:chits.filter((c)=>same(c.target,t.country)) })), portfolioProfile:{ summary:portfolioAgenda.portfolioPosition || masterContext.portfolioStance || 'Portfolio + Agenda Intelligence Packet', interests:portfolioAgenda.portfolioObjectives || [], sources:portfolioAgenda.sources || [] }, recommendedTargets:targetPool.targets.map((t)=>({ name:t.country, iso:t.iso, reason:t.reason, selectionType:t.selectionType })), metadata:{ researchPacketStats:researchPacket.stats, shortfall:output.shortfall, jobId }, researchSummary:'Five-stage IndexedDB-backed Gemini + official DDGS research pipeline' };
    mission.validationProblems=validateMissionResponse(mission,{ targetingMode, poiCount, portfolio:runtimeForm.portfolio, freezeDate:form.freezeDate });
    await store.put('jobs',{ ...job, status:'complete', completedAt:new Date().toISOString() });
    return { ...mission, researchPacket, modelInfo:{ mode:modelSelection?.modelMode || 'best' } };
  } catch (error) { await setStageStatus(store, jobId, activeStage, 'FAILED', { error:String(error.message || error) }); await runtimeLog({ store, jobId, onProgress, stage:activeStage, message:`[${activeStage.replace('_',' ').toUpperCase()}] FAILED: ${error.message || error}` }); await store.put('errors',{ id:`${jobId}_error_${Date.now()}`, jobId, stage:activeStage, error:String(error.message || error), category:error.category || 'unknown' }); await store.put('jobs',{ ...job, status:'failed', failedAt:new Date().toISOString() }); throw error; }
}

export async function generateFollowUp({ sliders, chit, apiKey, onProgress, modelSelection }) { await emit(onProgress,{stage:'follow_up',phase:'gemini',completed:0,total:1,detail:'Generating evidence-bounded follow-up.'}); const r=await callGemini(apiKey,`Return JSON {expectedEvasion,question}. Keep same evidence and uncertainty: ${compact(chit)}. Sliders:${compact(sliders)}`,{...modelSelection,schema:FOLLOW_UP_RESPONSE_SCHEMA}); const p=extractJson(r.text); validArtifact('FOLLOW_UP_RESPONSE',p,['expectedEvasion','question']); return {...chit,followUp:{expectedEvasion:p.expectedEvasion,question:p.question}}; }
export async function regenerateChit(args) { return generateFollowUp(args); }
export function buildMissionPrompt() { return 'Deprecated: generation is performed exclusively by the five-stage research pipeline.'; }
