import { callGemini, GeminiError, FOLLOW_UP_RESPONSE_SCHEMA } from './gemini.js';
import { extractJson } from './responseParser.js';
import { normalizeChit, validateMissionResponse } from './validation.js';
import { queryBudget, retrieveQueries, freezeValidation, clusterIncidents, targetValue, allocateActorQueries, MAX_POIS } from './ddgsResearch.js';

const JSON_SCHEMA = { type: 'object', properties: { queries: { type: 'array', items: { type: 'string' } }, actors: { type: 'array', items: { type: 'object' } }, intelligence: { type: 'object' }, evidence: { type: 'array', items: { type: 'object' } }, pois: { type: 'array', items: { type: 'object' } } } };
const safeJson = (text, fallback) => { try { return extractJson(text); } catch { return fallback; } };
const compact = (value, length = 38000) => JSON.stringify(value).slice(0, length);
const stageCall = async (apiKey, prompt, modelSelection, attachments = []) => safeJson((await callGemini(apiKey, prompt, { ...modelSelection, schema: JSON_SCHEMA, timeoutMs: 70000, attachments })).text, {});
const contextInput = (form, sliders, poiCount) => ({ committee: form.committee, mandate: form.mandate || form.committee, agenda: form.agenda, portfolio: form.portfolio, freezeDate: form.freezeDate || null, requestedPOIs: poiCount, sliders, researchNotes: { text: form.researchNotes || '', type: 'USER_PROVIDED_CONTEXT' }, backgroundGuide: form.backgroundGuideText || form.backgroundGuide?.text || '' });
const expandQueries = (queries, count) => { const clean = [...new Set((queries || []).map((q) => String(q).trim()).filter(Boolean))]; if (!clean.length) return []; return Array.from({ length: count }, (_, i) => clean[i % clean.length]); };

export function lengthInfo(length) { const [, min, max, lines] = [[10,8,15,'≈ 1 line'],[25,15,25,'≈ 1–2 lines'],[40,20,35,'≈ 2 lines'],[55,30,45,'≈ 2–3 lines'],[70,40,55,'≈ 3 lines'],[85,50,70,'≈ 3–4 lines'],[100,65,90,'≈ 4–5 lines']].find(([limit]) => length <= limit); return { min, max, lines, words:`approximately ${min}–${max} words` }; }

// Stage 0 intentionally includes the notes as unverified context, never evidence.
export async function stage0BuildContextIntelligence({ form, sliders, poiCount, modelSelection, onProgress }) {
  onProgress?.({ stage: 'READING AGENDA', detail: 'Stage 0: Gemini is building the Master Context Packet.', done: 0, total: 1 });
  const input = contextInput(form, sliders, poiCount);
  const plan = await stageCall(form.apiKey, `Stage 0 Context Intelligence. Return JSON with queries (Gemini-generated, primary-source-focused) and intelligence. Research notes are USER_PROVIDED_CONTEXT, not verified facts. Background guide is contextual only. Required intelligence keys: committee, mandate, agenda, keyIssues, definitions, historicalContext, majorActors, existingMechanisms, relevantResolutions, treaties, statistics, ambiguities, importantDates, researchPriorities. Input: ${compact(input)}`, modelSelection, form.backgroundGuide?.data ? [form.backgroundGuide] : []);
  const sources = await retrieveQueries(expandQueries(plan.queries, Math.min(20, Math.max(5, poiCount))), { controversy: sliders.controversy, stage: 0, onProgress, freezeDate: form.freezeDate });
  const intelligence = await stageCall(form.apiKey, `Stage 0 Context Intelligence synthesis. Produce the required structured intelligence from this input and sources. Do not turn research notes/background guide into verified facts. Sources: ${compact(sources)}. Input: ${compact(input)}`, modelSelection);
  return { ...intelligence, userProvidedContext: input.researchNotes, portfolioForeignPolicySources: sources, sourceType: 'MASTER_CONTEXT_PACKET' };
}

export async function stage1DiscoverActors({ form, masterContext, poiCount, modelSelection, onProgress }) {
  const budget = queryBudget(poiCount).stage1;
  const plan = await stageCall(form.apiKey, `Stage 1 Actor Discovery. Begin with Gemini reasoning and return exactly ${budget} agenda-relevance queries plus candidate actors. Never seek scandal, controversy, misconduct, or aggression; actor relevance is agenda relevance only. Include countries, institutions, blocs, affected states and negotiating parties. Context: ${compact(masterContext)}`, modelSelection);
  const sources = await retrieveQueries(expandQueries(plan.queries, budget), { stage: 1, onProgress, freezeDate: form.freezeDate });
  const actorResult = await stageCall(form.apiKey, `Stage 1 Actor Discovery. Rank agenda-relevant actors only using Master Context and deduplicated retrieval. Return {actors:[{country,iso,relevance,reason,evidence:[{title,url,snippet,reason}]}]}. Exclude portfolio ${form.portfolio}. Sources: ${compact(sources)}`, modelSelection);
  const actors = (actorResult.actors || plan.actors || []).filter((a) => a?.country && !same(a.country, form.portfolio)).map((a) => ({ ...a, source: 'AUTO_DISCOVERED', relevance: Math.max(0, Math.min(100, Number(a.relevance) || 50)), evidence: Array.isArray(a.evidence) ? a.evidence : [] })).sort((a,b) => b.relevance-a.relevance);
  return { actors, sources, queryBudget: budget, queriesExecuted: budget };
}

export async function stage2BuildTargetIntelligence({ form, sliders, poiCount, masterContext, actorPool, selectedTargets = [], targetingMode, modelSelection, onProgress }) {
  const manualActors = selectedTargets.filter((target) => !same(target.name, form.portfolio)).map((target) => ({ ...target, source: 'USER_SELECTED_OPPOSITION', relevance: 0, reason: 'Explicit manual opposition selection; not an agenda-relevance score.', evidence: [] }));
  const actorMap = new Map(actorPool.actors.map((actor) => [actor.iso || actor.country, actor])); manualActors.forEach((actor) => { const key = actor.iso || actor.name; actorMap.set(key, actorMap.has(key) ? { ...actorMap.get(key), userSelected: true } : actor); });
  const researchActors = [...actorMap.values()]; const eligibleActors = targetingMode === 'selected_only' ? researchActors.filter((actor) => actor.source === 'USER_SELECTED_OPPOSITION' || actor.userSelected) : researchActors;
  const budget = queryBudget(poiCount).stage2; const allocation = allocateActorQueries(eligibleActors, budget);
  const plan = await stageCall(form.apiKey, `Stage 2 Target Intelligence. Gemini must generate exactly ${budget} query strings and all query language/categories. Research these Stage-1 agenda-relevant actors plus explicitly user-selected opposition actors. Manual actors are included only by user request, not because they are agenda-relevant: ${compact(eligibleActors)}. Use controversy=${sliders.controversy} to set controversial-evidence depth and aggression=${sliders.aggression} only as later rhetorical force, not evidence standards. Allocate query count by actor relevance while reserving coverage for each manual actor: ${compact(allocation)}. Context: ${compact(masterContext)}`, modelSelection);
  const sources = await retrieveQueries(expandQueries(plan.queries, budget), { controversy: sliders.controversy, stage: 2, onProgress, freezeDate: form.freezeDate });
  const classified = await stageCall(form.apiKey, `Stage 2 evidence classification. Structurally classify retrieved source clusters. Return evidence array, each with country, category, claim, date, eventDate, publicationDate, informationAvailabilityDate, epistemicStatus (ALLEGED|INVESTIGATED|REPORTED|DISPUTED|CONFIRMED|COURT_ESTABLISHED|OFFICIALLY_DOCUMENTED), agendaRelevance 0-100, evidenceStrength 0-100, sourceQuality 0-100, isAllegation, primarySourceFound, sourceIds (only IDs from sources), legalAccountability, controversyFit, recency. Preserve uncertainty. Sources: ${compact(sources.map((s,i) => ({...s,id:`research_${i+1}`})))}. Actors: ${compact(actorPool.actors)}`, modelSelection);
  const indexed = sources.map((s, i) => ({ ...s, id: `research_${i + 1}` })); const ids = new Set(indexed.map((s) => s.id));
  const evidence = (classified.evidence || []).map((e) => { const sourceIds = (e.sourceIds || []).filter((id) => ids.has(id)); const date = freezeValidation({ publicationDate:e.publicationDate, eventDate:e.eventDate, informationAvailabilityDate:e.informationAvailabilityDate, freezeDate:form.freezeDate }); return { ...e, sourceIds, freezeDate: form.freezeDate || null, ...date }; }).filter((e) => e.sourceIds.length && e.usable && Number(e.agendaRelevance) > 0);
  const incidents = clusterIncidents(evidence).map((incident) => { const es = incident.evidence; const c = es.reduce((best,e) => ({ agendaRelevance:Math.max(best.agendaRelevance,Number(e.agendaRelevance)||0), evidenceStrength:Math.max(best.evidenceStrength,Number(e.evidenceStrength)||0), legalAccountability:Math.max(best.legalAccountability,Number(e.legalAccountability)||0), controversyFit:Math.max(best.controversyFit,Number(e.controversyFit)||0), recency:Math.max(best.recency,Number(e.recency)||0), sourceQuality:Math.max(best.sourceQuality,Number(e.sourceQuality)||0), corroboration:Math.max(best.corroboration,Math.min(100, es.length*35)) }), { corroboration:0 }); return { ...incident, components:c, targetValue:targetValue(c) }; }).sort((a,b) => b.targetValue-a.targetValue);
  return { sources:indexed, evidence, incidents, actors: eligibleActors, queryBudget:budget, queriesExecuted:budget };
}

function same(a,b) { return String(a||'').trim().toLowerCase() === String(b||'').trim().toLowerCase(); }
function evidenceFor(ids, intelligence) { const wanted = new Set(ids); return intelligence.sources.filter((s) => wanted.has(s.id)); }
function epistemicPrefix(status) { return ({ ALLEGED:'Reports have raised allegations', INVESTIGATED:'An investigation found', REPORTED:'Reports indicate', DISPUTED:'Reports have alleged this, while the target disputes it' })[status] || ''; }
export async function stage3GeneratePOIs({ form, sliders, poiCount, includeFollowUp, masterContext, actorPool, targetIntelligence, modelSelection, onProgress }) {
  const info = lengthInfo(sliders.length); const incidents = targetIntelligence.incidents.filter((i) => i.targetValue > 0);
  const prompt = `Stage 3 POI Generation. Begin with Gemini reasoning. Generate exactly ${poiCount} JSON POIs when enough incidents exist, using each incident at most once. Gemini MUST output evidenceIds only, never URLs. Contract {poi,targetCountry,evidenceIds,classification,epistemicStatus,sliderCompliance}. Evidence IDs must be selected exactly from supplied incidents. Aggression ${sliders.aggression} controls directness, diplomacy ${sliders.diplomacy} controls polish only, controversy ${sliders.controversy} controls evidence selection, length must be ${info.min}-${info.max} words. Follow-up generation is ${includeFollowUp ? 'enabled' : 'disabled'} and does not authorize new evidence. Prefix uncertain claims appropriately: ALLEGED '${epistemicPrefix('ALLEGED')}', INVESTIGATED '${epistemicPrefix('INVESTIGATED')}', REPORTED '${epistemicPrefix('REPORTED')}', DISPUTED '${epistemicPrefix('DISPUTED')}'. Do not invent facts. Context: ${compact(masterContext,12000)}. Actors: ${compact(actorPool.actors,8000)}. Incidents: ${compact(incidents,40000)}`;
  let generated = (await stageCall(form.apiKey, prompt, modelSelection)).pois || []; const used = new Set(); const valid = [];
  const accept = (item) => { const incident = incidents.find((x) => x.country === item.targetCountry && x.evidenceIds.some((id) => (item.evidenceIds || []).includes(id))); const evidence = evidenceFor(item.evidenceIds || [], targetIntelligence); const words = String(item.poi || '').trim().split(/\s+/).filter(Boolean).length; const compliance = item.sliderCompliance || {}; const slidersMatch = ['aggression', 'controversy', 'diplomacy', 'length'].every((key) => Number(compliance[key]) === Number(sliders[key])); if (!incident || !evidence.length || used.has(incident.id) || words < info.min || words > info.max || !slidersMatch || same(item.targetCountry, form.portfolio)) return false; used.add(incident.id); valid.push({ ...item, evidence, incident }); return true; };
  generated.forEach(accept);
  // Regenerate only failed slots with unused verified incident IDs.
  for (let attempt=0; valid.length < poiCount && attempt<3 && incidents.some((i)=>!used.has(i.id)); attempt+=1) { const missing=poiCount-valid.length; const retry=await stageCall(form.apiKey, `${prompt}\nRegenerate exactly ${missing} missing slots using ONLY these unused incidents: ${compact(incidents.filter((i)=>!used.has(i.id)))}`, modelSelection); (retry.pois||[]).forEach(accept); }
  onProgress?.({ stage:'GENERATING POIs', detail:`Stage 3 validated ${valid.length}/${poiCount} POIs.`, done:valid.length,total:poiCount });
  return { pois:valid, shortfall:Math.max(0,poiCount-valid.length) };
}

export async function generateMission(args) {
  const { form, sliders, selectedTargets, targetingMode, includeFollowUp, poiCount, onProgress, modelSelection } = args;
  if (!Number.isInteger(poiCount) || poiCount < 1 || poiCount > MAX_POIS) throw new GeminiError('POI count must be between 1 and 100.', { category:'invalid-poi-count' });
  const masterContext = await stage0BuildContextIntelligence({ form, sliders, poiCount, modelSelection, onProgress });
  const actorPool = await stage1DiscoverActors({ form, masterContext, poiCount, modelSelection, onProgress });
  const targetIntelligence = await stage2BuildTargetIntelligence({ form, sliders, poiCount, masterContext, actorPool, selectedTargets, targetingMode, modelSelection, onProgress });
  const output = await stage3GeneratePOIs({ form, sliders, poiCount, includeFollowUp, masterContext, actorPool, targetIntelligence, modelSelection, onProgress });
  const chits = output.pois.map((p) => normalizeChit({ target:p.targetCountry, poi:p.poi, evidence:p.evidence, classification:p.classification, documented_contradiction:p.incident.claims?.[0] || '', legal_foundation:p.incident.evidence?.[0]?.category || '', tactical_impact:'Evidence-backed agenda pressure point.', pressurePoint:{ portfolioPosition: 'Master Context Packet portfolio analysis', targetPositionAction:p.incident.claims?.[0]||'', conflict:p.incident.claims?.[0]||'', agendaRelevance:String(p.incident.components.agendaRelevance) }, legalTacticalTypes:[p.classification], epistemicStatus:p.epistemicStatus, sliderCompliance:p.sliderCompliance }, { form, sliders, includeFollowUp }));
  const researchPacket={ masterContext, actorPool, targetIntelligence, stats:{ stage1Queries:actorPool.queriesExecuted, stage2Queries:targetIntelligence.queriesExecuted, retainedUrls:targetIntelligence.sources.length, incidents:targetIntelligence.incidents.length }, sources:targetIntelligence.sources };
  const mission={ chits, targets:actorPool.actors.map((a)=>({country:a.country,pois:chits.filter((c)=>same(c.target,a.country))})), portfolioProfile:{ summary:masterContext.portfolioForeignPolicy || masterContext.agenda || 'Master Context Packet', interests:[],sources:[] }, recommendedTargets:actorPool.actors.map(({country,iso,reason})=>({name:country,iso,reason})), metadata:{researchPacketStats:researchPacket.stats,shortfall:output.shortfall}, researchSummary:'Four-stage Gemini + DDGS research pipeline' };
  mission.validationProblems=validateMissionResponse(mission,{targetingMode,poiCount,portfolio:form.portfolio,freezeDate:form.freezeDate});
  return { ...mission, researchPacket, modelInfo:{ mode:modelSelection?.modelMode || 'best' } };
}

export async function generateFollowUp({ sliders, chit, apiKey, onProgress, modelSelection }) { onProgress?.({stage:'GENERATING FOLLOW-UP',detail:'Generating evidence-bounded follow-up.',done:0,total:1}); const r=await callGemini(apiKey,`Return JSON {expectedEvasion,question}. Keep the same evidence and pressure: ${compact(chit)}. Sliders:${compact(sliders)}`,{...modelSelection,schema:FOLLOW_UP_RESPONSE_SCHEMA}); const p=safeJson(r.text,{}); return {...chit,followUp:{expectedEvasion:p.expectedEvasion||'The delegation may deny the documented record.',question:p.question||'How does the delegation reconcile this documented record?'}}; }
export async function regenerateChit({ sliders, chit, apiKey, onProgress, modelSelection }) { return generateFollowUp({sliders,chit,apiKey,onProgress,modelSelection}); }
export function buildMissionPrompt() { return 'Deprecated: generation is performed exclusively by the four-stage research pipeline.'; }
