import assert from 'node:assert/strict';
import { allocateActorQueries, canonicalUrl, clusterIncidents, deduplicateSources, freezeValidation, newsShare, pooled, queryBudget, retrieveQueries, targetValue } from './ddgsResearch.js';
import { resolveCountry, searchCountries } from './countrySearch.js';

for (const count of [1, 10, 20, 50, 100]) { const budget = queryBudget(count); assert.equal(budget.stage1, count * 6); assert.equal(budget.stage2, count * 8); assert.equal(budget.stage3, count * 4); }
assert.deepEqual(queryBudget(20), { stage1: 120, stage2: 160, stage3: 80 });
assert.deepEqual(queryBudget(100), { stage1: 600, stage2: 800, stage3: 400 });
assert.equal(newsShare(0), .2); assert.equal(newsShare(45), .5); assert.equal(newsShare(70), .7); assert.equal(newsShare(100), .85);
assert.equal(canonicalUrl('https://www.un.org/a/?utm_source=x#part'), 'https://un.org/a');
assert.equal(deduplicateSources([{ canonicalUrl:'https://x.test' }, { canonicalUrl:'https://x.test' }]).length, 1);
assert.deepEqual(freezeValidation({ publicationDate:'2026-02-01', freezeDate:'2026-03-01' }), { freezeStatus:'PRE_FREEZE', usable:true });
assert.deepEqual(freezeValidation({ publicationDate:'2026-04-01', eventDate:'2026-02-01', informationAvailabilityDate:'2026-02-15', freezeDate:'2026-03-01' }), { freezeStatus:'POST_FREEZE_PRE_FREEZE_EVENT', usable:true });
assert.deepEqual(freezeValidation({ publicationDate:'2026-04-01', eventDate:'2026-04-01', informationAvailabilityDate:'2026-04-01', freezeDate:'2026-03-01' }), { freezeStatus:'POST_FREEZE_NEW_EVENT', usable:false });
const clusters = clusterIncidents([{ country:'A', claim:'Court found the same implementation failure', sourceIds:['research_1'] }, { country:'A', claim:'Implementation failure found by court same', sourceIds:['research_2'] }]);
assert.equal(clusters.length, 1, 'incident clustering combines corroboration');
const allocated = allocateActorQueries([{ relevance:90 }, { relevance:10 }, { relevance:1 }], 100);
assert.equal(allocated[0].queryAllocation > 50, true);
assert.equal(allocated.reduce((sum, actor) => sum + actor.queryAllocation, 0), 100, 'actor allocation remains the total stage budget');
assert.deepEqual(allocateActorQueries([], 100), []);
assert.equal(targetValue({ agendaRelevance:100, evidenceStrength:100, legalAccountability:100, controversyFit:100, recency:100, sourceQuality:100, corroboration:100 }), 100);
assert.equal(resolveCountry(' People\'s Republic of China ').iso, 'CHN');
assert.equal(resolveCountry('USA').name, 'United States');
assert(searchCountries('united stat').some((country) => country.iso === 'USA'), 'partial country search returns an autocomplete match');
const indexed = await pooled(['first', 'second', 'third'], async (value, index) => { await new Promise((resolve) => setTimeout(resolve, (2 - index) * 3)); return `${index}:${value}`; }, 3);
assert.deepEqual(indexed, ['0:first', '1:second', '2:third'], 'pooled work retains stable input order and indexes');
const progress = [];
const retrieval = await retrieveQueries(['a', 'b', 'c'], { stage:2, controversy:70, extractionBudget:3, onProgress:(event) => progress.push(event), search:async (query) => query === 'b' ? { results:[], error:'timeout' } : { results:[{ href:`https://example.test/${query}`, title:query }] }, extract:async () => ({ content:'page', error:null }) });
assert.deepEqual(progress.map((event) => event.done ?? event.completed), [3], 'progress advances by persisted DDGS batch without NaN');
assert(progress.every((event) => Number.isFinite(event.done) && event.total === 3), 'progress counters are finite');
assert.deepEqual(retrieval.diagnostics, { attempted:3, successful:2, failed:1, empty:0, extracted:2, usableAfterFreeze:2 });
console.log('five-stage research planning tests passed');
